config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'artists#index'

  resources :artists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :genres

    paginates_per 20

    validates :name, presence: true
    validates :genre1, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
	belongs_to :artists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    if params[:query].present?
      @artists = Artist.where("name LIKE ?", "%#{params[:query]}%").page params[:page]
    else
      @artists = Artist.order(created_at: :desc).page params[:page]
    end
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @genres = Genre.all
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])

    if @artist.update(artist_params)
      redirect_to artists_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :genre1, :genre2, :genre3, :year, :region, :collectif)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.list
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/artists/_new.html.erb
<%= simple_form_for @artist do |f| %>
  <%= f.input :name, label: 'Enter Artist name', error: 'Username is mandatory, please specify one'  %>
  <%= f.input :genre1, label: 'Please select a genre', collection: Genre.all, label_method: :name, value_method: :name %>
  <%= f.input :genre2, label: 'Please select another genre', collection: Genre.all, label_method: :name, value_method: :name %>
  <%= f.input :genre3, label: 'Please select an extra genre', collection: Genre.all, label_method: :name, value_method: :name %>
  <%= f.input :year %>
  <%= f.input :collectif %>
  <%= f.input :region %>
  <%= f.button :submit %>
<% end %>

app/views/artists/edit.html.erb
<div class="container">

<h1 class="display-5">Edit <%= @artist.name %> information</h1>


<%= render "new" %>
</div>

app/views/artists/index.html.erb
<div class="container">
    <%= raw "<br>" %>
  <div class="header">
      <%= link_to "New Artist", new_artist_path, class: "btn btn-primary"%>
  </div>
  
  <%= raw "<br>" %>
  
  <%= link_to_prev_page @artists, 'Prev Page' %> <%= link_to_next_page @artists, 'Next Page' %>
  <table class="table table-striped table-sm">
    <thead>
      <tr>

        <th>Name</th>
        <th>Year</th>
        <th>Region</th>
        <th>Genre 1</th>
        <th>Genre 2</th>
        <th>Genre 3</th>
        <th>Collectif</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
        <% @artists.each do |artist| %>
          <tr>
            <td><%= artist.name %></td>
            <td><%= artist.year %></td>
            <td><%= artist.region %></td>
            <td><%= artist.genre1 %></td>
            <td><%= artist.genre2 %></td>
            <td><%= artist.genre3 %></td>
            <td><%= artist.collectif %></td>
            <td><%= link_to "Edit", edit_artist_path(artist), class: "btn btn-secondary"%></td>
          </tr>
        <% end %>
    </tbody>
  </table>


</div>

app/views/artists/new.html.erb
<div class="container">

<h1 class="display-5">Add a new artist by filling its information</h1>


<%= render "new" %>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">HipHopHub</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
      <%= form_with(url: artists_path, method: :get, data: {turbo_frame: "artist"}) do |form| %>
        <%= form.label :query, "Search by artist name:" %>
        <div>
          <%= form.text_field :query %>
          <%= form.submit 'Search'%>
        </div>
      <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HipHop Hub - The Hiphop and Rap knowledge hub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= favicon_link_tag asset_path('favicon.png') %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
    <%= render "layouts/navbar" %>
    <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
  
</html>